###   glob-coord.jl   ###
### GENERATED BY save_globcoord_db() FUNCTION ###
###         IN coordinate-management.jl       ###
###   23/07/2025 00:57   ###

GLOB_COORD_DB = [


### Alchemy ###
# (1) alch_blood_exp
fstone_globcoord("alch_blood_exp", "X_alch_blood_exp", "SOLO_VAR", "670", "0", "Alchemy", "description")
;
# (2) alch_dust_exp
fstone_globcoord("alch_dust_exp", "X_alch_dust_exp", "SOLO_VAR", "923", "0", "Alchemy", "description")
;
# (3) alch_coin_exp
fstone_globcoord("alch_coin_exp", "X_alch_coin_exp", "SOLO_VAR", "1180", "0", "Alchemy", "description")
;
# (4) alch_experiments
fstone_globcoord("alch_experiments", "Y_alch_experiments", "SOLO_VAR", "709", "0", "Alchemy", "description")
;
# (5) alch_close_gem
fstone_globcoord("alch_close_gem", "X_alch_close_gem", "Y_alch_close_gem", "943", "354", "Alchemy", "description")
;


### CheckIn ###
# (1) main_shop
fstone_globcoord("main_shop", "X_main_shop", "Y_main_shop", "922", "432", "CheckIn", "description")
;
# (2) free_box
fstone_globcoord("free_box", "X_free_box", "Y_free_box", "469", "631", "CheckIn", "description")
;
# (3) checkin_tab
fstone_globcoord("checkin_tab", "X_checkin_tab", "Y_checkin_tab", "989", "239", "CheckIn", "description")
;
# (4) checkin_but
fstone_globcoord("checkin_but", "X_checkin_but", "Y_checkin_but", "960", "744", "CheckIn", "description")
;
# (5) daily_quests
fstone_globcoord("daily_quests", "X_daily_quests", "Y_daily_quests", "552", "258", "CheckIn", "description")
;
# (6) weekly_quests
fstone_globcoord("weekly_quests", "X_weekly_quests", "Y_weekly_quests", "828", "257", "CheckIn", "description")
;
# (7) quests_claim
fstone_globcoord("quests_claim", "X_quests_claim", "Y_quests_claim", "1116", "368", "CheckIn", "description")
;


### Exotic ###
# (1) exo_toggle
fstone_globcoord("exo_toggle", "X_exo_toggle", "Y_exo_toggle", "1246", "330", "Exotic", "description")
;
# (2) speed_scroll
fstone_globcoord("speed_scroll", "X_speed_scroll", "Y_speed_scroll", "673", "580", "Exotic", "description")
;
# (3) damage_scroll
fstone_globcoord("damage_scroll", "X_damage_scroll", "Y_damage_scroll", "909", "581", "Exotic", "description")
;
# (4) health_scroll
fstone_globcoord("health_scroll", "X_health_scroll", "Y_health_scroll", "1144", "580", "Exotic", "description")
;
# (5) midas_touch
fstone_globcoord("midas_touch", "X_midas_touch", "Y_midas_touch", "695", "808", "Exotic", "description")
;
# (6) drum_war
fstone_globcoord("drum_war", "X_drum_war", "Y_drum_war", "1153", "374", "Exotic", "description")
;
# (7) dragon_armor
fstone_globcoord("dragon_armor", "X_dragon_armor", "Y_dragon_armor", "686", "588", "Exotic", "description")
;
# (8) guardian_rune
fstone_globcoord("guardian_rune", "X_guardian_rune", "Y_guardian_rune", "923", "589", "Exotic", "description")
;
# (9) totem_agony
fstone_globcoord("totem_agony", "X_totem_agony", "Y_totem_agony", "1136", "583", "Exotic", "description")
;
# (10) totem_annihil
fstone_globcoord("totem_annihil", "X_totem_annihil", "Y_totem_annihil", "678", "812", "Exotic", "description")
;
# (11) exotic_scroll
fstone_globcoord("exotic_scroll", "X_exotic_scroll", "SOLO_VAR", "559", "0", "Exotic", "description")
;
# (12) exotic_scroll_bottom
fstone_globcoord("exotic_scroll_bottom", "Y_exotic_scroll_bottom", "SOLO_VAR", "844", "0", "Exotic", "description")
;
# (13) exotic_scroll_top
fstone_globcoord("exotic_scroll_top", "Y_exotic_scroll_top", "SOLO_VAR", "388", "0", "Exotic", "description")
;


### Guardian ###
# (1) guard_train
fstone_globcoord("guard_train", "X_guard_train", "Y_guard_train", "812", "708", "Guardian", "description")
;


### Guild ###
# (1) guild_portal
fstone_globcoord("guild_portal", "X_guild_portal", "Y_guild_portal", "1048", "285", "Guild", "description")
;
# (2) exped
fstone_globcoord("exped", "X_exped", "Y_exped", "226", "409", "Guild", "description")
;
# (3) exped_but
fstone_globcoord("exped_but", "X_exped_but", "Y_exped_but", "944", "389", "Guild", "description")
;
# (4) guild_hall
fstone_globcoord("guild_hall", "X_guild_hall", "Y_guild_hall", "776", "485", "Guild", "description")
;
# (5) applications
fstone_globcoord("applications", "X_applications", "Y_applications", "657", "850", "Guild", "description")
;
# (6) accept_player
fstone_globcoord("accept_player", "X_accept_player", "Y_accept_player", "854", "317", "Guild", "description")
;
# (7) guild_shop
fstone_globcoord("guild_shop", "X_guild_shop", "Y_guild_shop", "464", "337", "Guild", "description")
;
# (8) guild_supplies
fstone_globcoord("guild_supplies", "X_guild_supplies", "Y_guild_supplies", "159", "689", "Guild", "description")
;
# (9) claim_pickaxe
fstone_globcoord("claim_pickaxe", "X_claim_pickaxe", "Y_claim_pickaxe", "510", "466", "Guild", "description")
;


### Map ###
# (1) map_mission_start
fstone_globcoord("map_mission_start", "X_map_mission_start", "Y_map_mission_start", "696", "792", "Map", "description")
;
# (2) map_mission_claim
fstone_globcoord("map_mission_claim", "X_map_mission_claim", "Y_map_mission_claim", "156", "385", "Map", "description")
;
# (3) map_idle_notif_ul
fstone_globcoord("map_idle_notif_ul", "x_map_idle_notif_ul", "y_map_idle_notif_ul", "344", "854", "Map", "description")
;
# (4) map_idle_notif_br
fstone_globcoord("map_idle_notif_br", "x_map_idle_notif_br", "y_map_idle_notif_br", "853", "876", "Map", "description")
;


### Oracle ###
# (1) ritual
fstone_globcoord("ritual", "X_ritual", "Y_ritual", "593", "457", "Oracle", "description")
;
# (2) ritual_1
fstone_globcoord("ritual_1", "X_ritual_1", "Y_ritual_1", "835", "750", "Oracle", "description")
;
# (3) ritual_2
fstone_globcoord("ritual_2", "X_ritual_2", "Y_ritual_2", "1133", "510", "Oracle", "description")
;
# (4) ritual_3
fstone_globcoord("ritual_3", "X_ritual_3", "Y_ritual_3", "838", "513", "Oracle", "description")
;
# (5) ritual_4
fstone_globcoord("ritual_4", "X_ritual_4", "Y_ritual_4", "1124", "758", "Oracle", "description")
;
# (6) oracle_shop
fstone_globcoord("oracle_shop", "X_oracle_shop", "Y_oracle_shop", "587", "703", "Oracle", "description")
;
# (7) oracle_gift
fstone_globcoord("oracle_gift", "X_oracle_gift", "Y_oracle_gift", "476", "569", "Oracle", "description")
;


### Research ###
# (1) ftree_tab
fstone_globcoord("ftree_tab", "X_ftree_tab", "Y_ftree_tab", "1256", "594", "Research", "description")
;
# (2) ftree_start
fstone_globcoord("ftree_start", "X_ftree_start", "Y_ftree_start", "571", "691", "Research", "description")
;
# (3) ftree_claim
fstone_globcoord("ftree_claim", "X_ftree_claim", "Y_ftree_claim", "429", "828", "Research", "description")
;
# (4) ftree_scroll
fstone_globcoord("ftree_scroll", "Y_ftree_scroll", "SOLO_VAR", "276", "0", "Research", "description")
;
# (5) ftree_scroll_right
fstone_globcoord("ftree_scroll_right", "X_ftree_scroll_right", "SOLO_VAR", "697", "0", "Research", "description")
;
# (6) ftree_scroll_left
fstone_globcoord("ftree_scroll_left", "X_ftree_scroll_left", "SOLO_VAR", "355", "0", "Research", "description")
;
# (7) ftree_rew_test_ul
fstone_globcoord("ftree_rew_test_ul", "x_ftree_rew_test_ul", "y_ftree_rew_test_ul", "55", "371", "Research", "description")
;
# (8) ftree_rew_test_br
fstone_globcoord("ftree_rew_test_br", "x_ftree_rew_test_br", "y_ftree_rew_test_br", "154", "669", "Research", "description")
;


### Settings ###
# (1) server_switch
fstone_globcoord("server_switch", "X_server_switch", "Y_server_switch", "1046", "593", "Settings", "description")
;
# (2) fav_servers
fstone_globcoord("fav_servers", "X_fav_servers", "Y_fav_servers", "906", "285", "Settings", "description")
;
# (3) serv_confirm
fstone_globcoord("serv_confirm", "X_serv_confirm", "Y_serv_confirm", "784", "652", "Settings", "description")
;
# (4) more
fstone_globcoord("more", "X_more", "Y_more", "977", "209", "Settings", "description")
;
# (5) code
fstone_globcoord("code", "X_code", "Y_code", "456", "588", "Settings", "description")
;
# (6) submit
fstone_globcoord("submit", "X_submit", "Y_submit", "848", "592", "Settings", "description")
;
# (7) servname_ul
fstone_globcoord("servname_ul", "x_servname_ul", "y_servname_ul", "877", "442", "Settings", "description")
;
# (8) servname_br
fstone_globcoord("servname_br", "x_servname_br", "y_servname_br", "1210", "555", "Settings", "description")
;
# (9) switch_fav_ul
fstone_globcoord("switch_fav_ul", "x_switch_fav_ul", "y_switch_fav_ul", "352", "211", "Settings", "description")
;
# (10) switch_fav_br
fstone_globcoord("switch_fav_br", "x_switch_fav_br", "y_switch_fav_br", "1023", "320", "Settings", "description")
;
# (11) server_s1
fstone_globcoord("server_s1", "X_server_s1", "Y_server_s1", "898", "616", "Settings", "server switch button to s1 (6 favorites)")
;
# (12) server_s27
fstone_globcoord("server_s27", "X_server_s27", "Y_server_s27", "911", "395", "Settings", "server switch button to s27 (6 favorites)")
;
# (13) server_s31
fstone_globcoord("server_s31", "X_server_s31", "Y_server_s31", "397", "402", "Settings", "server switch button to s31 (6 favorites)")
;
# (14) server_s14
fstone_globcoord("server_s14", "X_server_s14", "Y_server_s14", "911", "499", "Settings", "server switch button to s14 (6 favorites)")
;
# (15) server_s8
fstone_globcoord("server_s8", "X_server_s8", "Y_server_s8", "410", "610", "Settings", "server switch button to s8 (6 favorites)")
;
# (16) server_s25
fstone_globcoord("server_s25", "X_server_s25", "Y_server_s25", "406", "503", "Settings", "server switch button to s25 (6 favorites)")
;


### StartQuit ###
# (1) WIN_POS
fstone_globcoord("WIN_POS", "X_WIN_POS", "Y_WIN_POS", "-26", "2", "StartQuit", "description")
;
# (2) firefox_menu
fstone_globcoord("firefox_menu", "X_firefox_menu", "Y_firefox_menu", "1357", "93", "StartQuit", "description")
;
# (3) firefox_quit
fstone_globcoord("firefox_quit", "X_firefox_quit", "Y_firefox_quit", "1298", "772", "StartQuit", "description")
;
# (4) load
fstone_globcoord("load", "X_load", "Y_load", "678", "565", "StartQuit", "description")
;
# (5) avatar
fstone_globcoord("avatar", "X_avatar", "Y_avatar", "105", "233", "StartQuit", "description")
;
# (6) irongard_ul
fstone_globcoord("irongard_ul", "x_irongard_ul", "y_irongard_ul", "501", "176", "StartQuit", "description")
;
# (7) irongard_br
fstone_globcoord("irongard_br", "x_irongard_br", "y_irongard_br", "881", "215", "StartQuit", "description")
;
# (8) url_ul
fstone_globcoord("url_ul", "x_url_ul", "y_url_ul", "258", "73", "StartQuit", "description")
;
# (9) url_br
fstone_globcoord("url_br", "x_url_br", "y_url_br", "1123", "103", "StartQuit", "description")
;
# (10) startref_ul
fstone_globcoord("startref_ul", "x_startref_ul", "y_startref_ul", "72", "699", "StartQuit", "description")
;
# (11) startref_br
fstone_globcoord("startref_br", "x_startref_br", "y_startref_br", "109", "732", "StartQuit", "description")
;


### WM ###
# (1) campaign_loot
fstone_globcoord("campaign_loot", "X_campaign_loot", "Y_campaign_loot", "150", "841", "WM", "description")
;
# (2) engi
fstone_globcoord("engi", "X_engi", "Y_engi", "906", "745", "WM", "description")
;
# (3) engi_shop
fstone_globcoord("engi_shop", "X_engi_shop", "Y_engi_shop", "454", "561", "WM", "description")
;
# (4) toolclaim
fstone_globcoord("toolclaim", "X_toolclaim", "Y_toolclaim", "1125", "656", "WM", "description")
;
# (5) camp_map
fstone_globcoord("camp_map", "X_camp_map", "Y_camp_map", "1271", "582", "WM", "description")
;
# (6) mission_button
fstone_globcoord("mission_button", "X_mission_button", "Y_mission_button", "1228", "857", "WM", "description")
;
# (7) liberations
fstone_globcoord("liberations", "X_liberations", "Y_liberations", "501", "724", "WM", "description")
;
# (8) dungeons
fstone_globcoord("dungeons", "X_dungeons", "Y_dungeons", "874", "720", "WM", "description")
;
# (9) dungeon_1
fstone_globcoord("dungeon_1", "X_dungeon_1", "Y_dungeon_1", "544", "697", "WM", "description")
;
# (10) dungeon_2
fstone_globcoord("dungeon_2", "X_dungeon_2", "Y_dungeon_2", "827", "699", "WM", "description")
;
# (11) liberation_1
fstone_globcoord("liberation_1", "X_liberation_1", "Y_liberation_1", "234", "697", "WM", "description")
;
# (12) liberation_2
fstone_globcoord("liberation_2", "X_liberation_2", "Y_liberation_2", "516", "697", "WM", "description")
;
# (13) liberation_3
fstone_globcoord("liberation_3", "X_liberation_3", "Y_liberation_3", "794", "695", "WM", "description")
;
# (14) liberation_4
fstone_globcoord("liberation_4", "X_liberation_4", "Y_liberation_4", "1047", "695", "WM", "description")
;
# (15) liber_scroll_right
fstone_globcoord("liber_scroll_right", "X_liber_scroll_right", "SOLO_VAR", "1035", "0", "WM", "description")
;
# (16) liber_scroll_left
fstone_globcoord("liber_scroll_left", "X_liber_scroll_left", "SOLO_VAR", "750", "0", "WM", "description")
;
# (17) liber_scroll
fstone_globcoord("liber_scroll", "Y_liber_scroll", "SOLO_VAR", "631", "0", "WM", "description")
;
# (18) north_island
fstone_globcoord("north_island", "X_north_island", "Y_north_island", "315", "811", "WM", "description")
;
# (19) battle_building
fstone_globcoord("battle_building", "X_battle_building", "Y_battle_building", "250", "296", "WM", "description")
;
# (20) campaign_access
fstone_globcoord("campaign_access", "X_campaign_access", "Y_campaign_access", "562", "529", "WM", "description")
;
]
