###   glob-coord.jl   ###
### GENERATED BY save_globcoord_db() FUNCTION ###
###         IN coordinate-management.jl       ###
###   14/11/2025 23:15   ###

GLOB_COORD_DB = [


### Alchemy ###
# (1) alch_blood_exp
fstone_globcoord("alch_blood_exp", "X_alch_blood_exp", "SOLO_VAR", "670", "0", "Alchemy", "start dragon blood alchemy experiment")
;
# (2) alch_dust_exp
fstone_globcoord("alch_dust_exp", "X_alch_dust_exp", "SOLO_VAR", "923", "0", "Alchemy", "start dust alchemy experiment")
;
# (3) alch_coin_exp
fstone_globcoord("alch_coin_exp", "X_alch_coin_exp", "SOLO_VAR", "1180", "0", "Alchemy", "exotic coin alchemy experiment")
;
# (4) alch_experiments
fstone_globcoord("alch_experiments", "Y_alch_experiments", "SOLO_VAR", "709", "0", "Alchemy", "common Y coordinate for all alchemy experiments")
;
# (5) alch_close_gem
fstone_globcoord("alch_close_gem", "X_alch_close_gem", "Y_alch_close_gem", "943", "354", "Alchemy", "close gems spending dialog in alchemy when misclicking on experiment spped-up")
;


### Bag ###
# (1) bag_slot_1_1
fstone_globcoord("bag_slot_1_1", "X_bag_slot_1_1", "Y_bag_slot_1_1", "1096", "418", "Bag", "bag slot line 1 column 1")
;
# (2) chest_open_10_max
fstone_globcoord("chest_open_10_max", "X_chest_open_10_max", "Y_chest_open_10_max", "746", "734", "Bag", "open button for 10 chests max - a manual correction is required after saving and before rewrite conf file, because of 1 chest and 10+ chests cases (calculate the X coordinate that suits to 3 configurations)")
;
# (3) mail_open
fstone_globcoord("mail_open", "X_mail_open", "Y_mail_open", "92", "714", "Bag", "open mail")
;
# (4) mail_delete
fstone_globcoord("mail_delete", "X_mail_delete", "Y_mail_delete", "1119", "828", "Bag", "delete mail and auto claim content")
;


### CheckIn ###
# (1) main_shop
fstone_globcoord("main_shop", "X_main_shop", "Y_main_shop", "922", "432", "CheckIn", "main gem shop")
;
# (2) free_box
fstone_globcoord("free_box", "X_free_box", "Y_free_box", "469", "631", "CheckIn", "free daily mystery box")
;
# (3) checkin_tab
fstone_globcoord("checkin_tab", "X_checkin_tab", "Y_checkin_tab", "989", "239", "CheckIn", "daily check-in tab")
;
# (4) checkin_but
fstone_globcoord("checkin_but", "X_checkin_but", "Y_checkin_but", "960", "744", "CheckIn", "daily check-in button when there is no special x2 offer")
;
# (5) daily_quests
fstone_globcoord("daily_quests", "X_daily_quests", "Y_daily_quests", "552", "258", "CheckIn", "daily quests selector in quest window")
;
# (6) weekly_quests
fstone_globcoord("weekly_quests", "X_weekly_quests", "Y_weekly_quests", "828", "257", "CheckIn", "weekly quests selector in quest window")
;
# (7) quests_claim
fstone_globcoord("quests_claim", "X_quests_claim", "Y_quests_claim", "1116", "368", "CheckIn", "daily/weekly quest claim button")
;


### Exotic ###
# (1) exo_toggle
fstone_globcoord("exo_toggle", "X_exo_toggle", "Y_exo_toggle", "1246", "330", "Exotic", "toggle to x10 s50 items for sale")
;
# (2) speed_scroll
fstone_globcoord("speed_scroll", "X_speed_scroll", "Y_speed_scroll", "673", "580", "Exotic", "sell speed scroll")
;
# (3) damage_scroll
fstone_globcoord("damage_scroll", "X_damage_scroll", "Y_damage_scroll", "909", "581", "Exotic", "sell damage scroll")
;
# (4) health_scroll
fstone_globcoord("health_scroll", "X_health_scroll", "Y_health_scroll", "1144", "580", "Exotic", "sell health scroll")
;
# (5) midas_touch
fstone_globcoord("midas_touch", "X_midas_touch", "Y_midas_touch", "695", "808", "Exotic", "sell midas touch")
;
# (6) drum_war
fstone_globcoord("drum_war", "X_drum_war", "Y_drum_war", "1153", "374", "Exotic", "sell drum of war")
;
# (7) dragon_armor
fstone_globcoord("dragon_armor", "X_dragon_armor", "Y_dragon_armor", "686", "588", "Exotic", "sell dragon armor")
;
# (8) guardian_rune
fstone_globcoord("guardian_rune", "X_guardian_rune", "Y_guardian_rune", "923", "589", "Exotic", "sell guardian rune")
;
# (9) totem_agony
fstone_globcoord("totem_agony", "X_totem_agony", "Y_totem_agony", "1136", "583", "Exotic", "sell totem of agony")
;
# (10) totem_annihil
fstone_globcoord("totem_annihil", "X_totem_annihil", "Y_totem_annihil", "678", "812", "Exotic", "sell totem of annihilation")
;
# (11) exotic_scroll
fstone_globcoord("exotic_scroll", "X_exotic_scroll", "SOLO_VAR", "559", "0", "Exotic", "X coordinate for item view drag down, on left side of item list")
;
# (12) exotic_scroll_bottom
fstone_globcoord("exotic_scroll_bottom", "Y_exotic_scroll_bottom", "SOLO_VAR", "844", "0", "Exotic", "Y coordinate for item view drag down, on bottom left side of item list")
;
# (13) exotic_scroll_top
fstone_globcoord("exotic_scroll_top", "Y_exotic_scroll_top", "SOLO_VAR", "388", "0", "Exotic", "Y coordinate for item view drag down, on upper left side of item list")
;


### Guardian ###
# (1) guard_train
fstone_globcoord("guard_train", "X_guard_train", "Y_guard_train", "812", "708", "Guardian", "train guardian button")
;
# (2) guard_slot_1
fstone_globcoord("guard_slot_1", "X_guard_slot_1", "SOLO_VAR", "533", "0", "Guardian", "first guardian slot starting from left")
;
# (3) guard_slot_2
fstone_globcoord("guard_slot_2", "X_guard_slot_2", "SOLO_VAR", "637", "0", "Guardian", "2nd guardian slot starting from left")
;
# (4) guard_slot_3
fstone_globcoord("guard_slot_3", "X_guard_slot_3", "SOLO_VAR", "736", "0", "Guardian", "3rd guardian slot starting from left")
;
# (5) guard_slot_4
fstone_globcoord("guard_slot_4", "X_guard_slot_4", "SOLO_VAR", "843", "0", "Guardian", "4th guardian slot starting from left")
;
# (6) guard_slot
fstone_globcoord("guard_slot", "Y_guard_slot", "SOLO_VAR", "841", "0", "Guardian", "all guardian slots Y coordinate")
;
# (7) guard_holy_tab
fstone_globcoord("guard_holy_tab", "X_guard_holy_tab", "Y_guard_holy_tab", "1024", "270", "Guardian", "tab for holy upgrades for guardians")
;
# (8) guard_holy_upgrade
fstone_globcoord("guard_holy_upgrade", "X_guard_holy_upgrade", "Y_guard_holy_upgrade", "1207", "677", "Guardian", "upgrade button of holy damage for guardians")
;
# (9) fight_boss
fstone_globcoord("fight_boss", "X_fight_boss", "Y_fight_boss", "1172", "492", "Guardian", "fight boss button of battlefield for auto guardian climb")
;


### Guild ###
# (1) guild_portal
fstone_globcoord("guild_portal", "X_guild_portal", "Y_guild_portal", "1048", "285", "Guild", "guild portal in town")
;
# (2) exped
fstone_globcoord("exped", "X_exped", "Y_exped", "226", "409", "Guild", "guild expedition building")
;
# (3) exped_but
fstone_globcoord("exped_but", "X_exped_but", "Y_exped_but", "913", "386", "Guild", "Guild expedition start and claim button")
;
# (4) guild_hall
fstone_globcoord("guild_hall", "X_guild_hall", "Y_guild_hall", "776", "485", "Guild", "guild hall building")
;
# (5) applications
fstone_globcoord("applications", "X_applications", "Y_applications", "657", "850", "Guild", "open guild applications window")
;
# (6) accept_player
fstone_globcoord("accept_player", "X_accept_player", "Y_accept_player", "854", "317", "Guild", "accept first player")
;
# (7) guild_shop
fstone_globcoord("guild_shop", "X_guild_shop", "Y_guild_shop", "464", "337", "Guild", "guild shop")
;
# (8) guild_supplies
fstone_globcoord("guild_supplies", "X_guild_supplies", "Y_guild_supplies", "159", "689", "Guild", "guild suuplies tab in shop")
;
# (9) claim_pickaxe
fstone_globcoord("claim_pickaxe", "X_claim_pickaxe", "Y_claim_pickaxe", "510", "466", "Guild", "claim free pickaxes")
;
# (10) guild_expe_but_ul
fstone_globcoord("guild_expe_but_ul", "x_guild_expe_but_ul", "y_guild_expe_but_ul", "841", "364", "Guild", "upper left corner of guild expedition button")
;
# (11) guild_expe_but_br
fstone_globcoord("guild_expe_but_br", "x_guild_expe_but_br", "y_guild_expe_but_br", "1033", "405", "Guild", "bottom right corner of guild expedition button")
;
# (12) arcane_crystal
fstone_globcoord("arcane_crystal", "X_arcane_crystal", "Y_arcane_crystal", "1165", "748", "Guild", "arcane crystal")
;
# (13) crystal_hit_toggle
fstone_globcoord("crystal_hit_toggle", "X_crystal_hit_toggle", "Y_crystal_hit_toggle", "1220", "800", "Guild", "arcane crystal x1 x5 x10 x20 toggle")
;
# (14) hit_arcane_crystal
fstone_globcoord("hit_arcane_crystal", "X_hit_arcane_crystal", "Y_hit_arcane_crystal", "687", "804", "Guild", "arcane crystal hit button")
;
# (15) chaos_rift
fstone_globcoord("chaos_rift", "X_chaos_rift", "Y_chaos_rift", "989", "587", "Guild", "chaos rift building")
;
# (16) chaos_rift_toggle
fstone_globcoord("chaos_rift_toggle", "X_chaos_rift_toggle", "Y_chaos_rift_toggle", "1223", "791", "Guild", "chaos rift x1 x5 x10 x20 hits toggle")
;
# (17) chaos_rift_hit
fstone_globcoord("chaos_rift_hit", "X_chaos_rift_hit", "Y_chaos_rift_hit", "691", "800", "Guild", "chaos rift hit button")
;


### Map ###
# (1) map_mission_start
fstone_globcoord("map_mission_start", "X_map_mission_start", "Y_map_mission_start", "696", "792", "Map", "start button on map mission pop up - pick a location on bottom letf of button area in order to avoid clash with cancel button")
;
# (2) map_mission_claim
fstone_globcoord("map_mission_claim", "X_map_mission_claim", "Y_map_mission_claim", "156", "385", "Map", "claim button of the top map mission in queue")
;
# (3) map_idle_notif_ul
fstone_globcoord("map_idle_notif_ul", "x_map_idle_notif_ul", "y_map_idle_notif_ul", "344", "854", "Map", "upper left corner of idle squad notification banner")
;
# (4) map_idle_notif_br
fstone_globcoord("map_idle_notif_br", "x_map_idle_notif_br", "y_map_idle_notif_br", "853", "876", "Map", "bottom right corner of idle squad notification banner")
;


### Oracle ###
# (1) ritual
fstone_globcoord("ritual", "X_ritual", "Y_ritual", "593", "457", "Oracle", "ritual tab in oracle")
;
# (2) ritual_1
fstone_globcoord("ritual_1", "X_ritual_1", "Y_ritual_1", "835", "750", "Oracle", "start/claim button of ritual 1")
;
# (3) ritual_2
fstone_globcoord("ritual_2", "X_ritual_2", "Y_ritual_2", "1133", "510", "Oracle", "start/claim button of ritual 2")
;
# (4) ritual_3
fstone_globcoord("ritual_3", "X_ritual_3", "Y_ritual_3", "838", "513", "Oracle", "start/claim button of ritual 3")
;
# (5) ritual_4
fstone_globcoord("ritual_4", "X_ritual_4", "Y_ritual_4", "1124", "758", "Oracle", "start/claim button of ritual 4")
;
# (6) oracle_shop
fstone_globcoord("oracle_shop", "X_oracle_shop", "Y_oracle_shop", "587", "703", "Oracle", "oracle shop tab")
;
# (7) oracle_gift
fstone_globcoord("oracle_gift", "X_oracle_gift", "Y_oracle_gift", "476", "569", "Oracle", "free daily oracle gift in shop")
;


### Research ###
# (1) ftree_tab
fstone_globcoord("ftree_tab", "X_ftree_tab", "Y_ftree_tab", "1256", "594", "Research", "Ftree tab in library")
;
# (2) ftree_start
fstone_globcoord("ftree_start", "X_ftree_start", "Y_ftree_start", "571", "691", "Research", "Start button for a Ftree research - open the node window first")
;
# (3) ftree_claim
fstone_globcoord("ftree_claim", "X_ftree_claim", "Y_ftree_claim", "429", "828", "Research", "left claim button of Ftree research")
;
# (4) ftree_scroll
fstone_globcoord("ftree_scroll", "Y_ftree_scroll", "SOLO_VAR", "276", "0", "Research", "Y coordinate for drag and drop one step - mouse sould be above Ftree during scrolling")
;
# (5) ftree_scroll_right
fstone_globcoord("ftree_scroll_right", "X_ftree_scroll_right", "SOLO_VAR", "697", "0", "Research", "X coordinate for Ftree scrolling starting at right side for a right to left drag and drop - one step of scrolling is horizontal length of a Ftree node")
;
# (6) ftree_scroll_left
fstone_globcoord("ftree_scroll_left", "X_ftree_scroll_left", "SOLO_VAR", "355", "0", "Research", "X coordinate for drop click at the left end side of Ftree scrolling - one step of scrolling is horizontal length of a Ftree node")
;
# (7) ftree_rew_test_ul
fstone_globcoord("ftree_rew_test_ul", "x_ftree_rew_test_ul", "y_ftree_rew_test_ul", "55", "371", "Research", "upper left corner of testing zone for rewind check - select a blue background on left side of rewinded Ftree")
;
# (8) ftree_rew_test_br
fstone_globcoord("ftree_rew_test_br", "x_ftree_rew_test_br", "y_ftree_rew_test_br", "154", "669", "Research", "bottom right corner of testing zone for rewind check - select a blue background on left side of rewinded Ftre")
;


### Settings ###
# (1) server_switch
fstone_globcoord("server_switch", "X_server_switch", "Y_server_switch", "1046", "593", "Settings", "server switch button in settings menu")
;
# (2) fav_servers
fstone_globcoord("fav_servers", "X_fav_servers", "Y_fav_servers", "906", "285", "Settings", "favorite server tab")
;
# (3) serv_confirm
fstone_globcoord("serv_confirm", "X_serv_confirm", "Y_serv_confirm", "784", "652", "Settings", "confirm server switch button")
;
# (4) more
fstone_globcoord("more", "X_more", "Y_more", "977", "209", "Settings", "more tab in settings menu")
;
# (5) code
fstone_globcoord("code", "X_code", "Y_code", "456", "588", "Settings", "gift code input form")
;
# (6) submit
fstone_globcoord("submit", "X_submit", "Y_submit", "848", "592", "Settings", "gift code submit button")
;
# (7) servname_ul
fstone_globcoord("servname_ul", "x_servname_ul", "y_servname_ul", "877", "442", "Settings", "upper left corner of server name zone")
;
# (8) servname_br
fstone_globcoord("servname_br", "x_servname_br", "y_servname_br", "1210", "555", "Settings", "bottom right corner of server name zone")
;
# (9) switch_fav_ul
fstone_globcoord("switch_fav_ul", "x_switch_fav_ul", "y_switch_fav_ul", "352", "211", "Settings", "upper left corner of a zone containing both 3 server selection filter tabs, for robustness control - checks if favorite server is selected")
;
# (10) switch_fav_br
fstone_globcoord("switch_fav_br", "x_switch_fav_br", "y_switch_fav_br", "1023", "320", "Settings", "upper left corner of a zone containing both 3 server selection filter tabs, for robustness control - checks if favorite server is selected")
;
# (11) server_s1
fstone_globcoord("server_s1", "X_server_s1", "Y_server_s1", "898", "616", "Settings", "server switch button to s1 (6 favorites)")
;
# (12) server_s27
fstone_globcoord("server_s27", "X_server_s27", "Y_server_s27", "911", "395", "Settings", "server switch button to s27 (6 favorites)")
;
# (13) server_s31
fstone_globcoord("server_s31", "X_server_s31", "Y_server_s31", "397", "402", "Settings", "server switch button to s31 (6 favorites)")
;
# (14) server_s14
fstone_globcoord("server_s14", "X_server_s14", "Y_server_s14", "911", "499", "Settings", "server switch button to s14 (6 favorites)")
;
# (15) server_s8
fstone_globcoord("server_s8", "X_server_s8", "Y_server_s8", "410", "610", "Settings", "server switch button to s8 (6 favorites)")
;
# (16) server_s25
fstone_globcoord("server_s25", "X_server_s25", "Y_server_s25", "406", "503", "Settings", "server switch button to s25 (6 favorites)")
;


### StartQuit ###
# (1) WIN_POS
fstone_globcoord("WIN_POS", "X_WIN_POS", "Y_WIN_POS", "-26", "2", "StartQuit", "firefox window position - this one has to be initialized with xdotool")
;
# (2) firefox_menu
fstone_globcoord("firefox_menu", "X_firefox_menu", "Y_firefox_menu", "1357", "93", "StartQuit", "menu icon of firefox on upper right side")
;
# (3) firefox_quit
fstone_globcoord("firefox_quit", "X_firefox_quit", "Y_firefox_quit", "1298", "772", "StartQuit", "quit firefox item in menu")
;
# (4) load
fstone_globcoord("load", "X_load", "Y_load", "678", "565", "StartQuit", "load game button (play icon) on firestone page of armor games")
;
# (5) avatar
fstone_globcoord("avatar", "X_avatar", "Y_avatar", "105", "233", "StartQuit", "avatar icon on top left")
;
# (6) irongard_ul
fstone_globcoord("irongard_ul", "x_irongard_ul", "y_irongard_ul", "501", "176", "StartQuit", "upper left corner of town irongard banner - for freeze detection")
;
# (7) irongard_br
fstone_globcoord("irongard_br", "x_irongard_br", "y_irongard_br", "881", "215", "StartQuit", "bottom right corner of town irongard banner - for freeze detection")
;
# (8) url_ul
fstone_globcoord("url_ul", "x_url_ul", "y_url_ul", "258", "73", "StartQuit", "upper left corner of url zone - firefox quit detection")
;
# (9) url_br
fstone_globcoord("url_br", "x_url_br", "y_url_br", "1123", "103", "StartQuit", "bottom right corner of url zone - forefox quit detection")
;
# (10) startref_ul
fstone_globcoord("startref_ul", "x_startref_ul", "y_startref_ul", "71", "700", "StartQuit", "upper left corner of mail icon in battlefield - for game start detection")
;
# (11) startref_br
fstone_globcoord("startref_br", "x_startref_br", "y_startref_br", "101", "732", "StartQuit", "bottom right corner of mail icon in battlefield - for game start detection")
;
# (12) failure_screen_ul
fstone_globcoord("failure_screen_ul", "x_failure_screen_ul", "y_failure_screen_ul", "200", "114", "StartQuit", "upper left corner of game view for faillure detection")
;
# (13) failure_screen_br
fstone_globcoord("failure_screen_br", "x_failure_screen_br", "y_failure_screen_br", "1187", "916", "StartQuit", "bottom right corner of game view for faillure detection")
;
# (14) accept_cookies
fstone_globcoord("accept_cookies", "X_accept_cookies", "Y_accept_cookies", "1115", "872", "StartQuit", "Accept cookies from Armor Games after expiration")
;
# (15) window_manager_start
fstone_globcoord("window_manager_start", "X_window_manager_start", "Y_window_manager_start", "11", "8", "StartQuit", "open window manager start menu for a non xterm firefox launch")
;
# (16) firefox_history
fstone_globcoord("firefox_history", "X_firefox_history", "Y_firefox_history", "1296", "314", "StartQuit", "history sub menu in firefox general menu")
;
# (17) firefox_erase_history
fstone_globcoord("firefox_erase_history", "X_firefox_erase_history", "Y_firefox_erase_history", "1274", "311", "StartQuit", "erase history sub menu in firefox history menu")
;
# (18) erase_confirm
fstone_globcoord("erase_confirm", "X_erase_confirm", "Y_erase_confirm", "836", "742", "StartQuit", "erase history confirmation button - user need to ensure that cache removal is always selected")
;
# (19) firefox_reload_page
fstone_globcoord("firefox_reload_page", "X_firefox_reload_page", "Y_firefox_reload_page", "133", "87", "StartQuit", "reload page icon in firefox")
;
# (20) skip_intro_dialog
fstone_globcoord("skip_intro_dialog", "X_skip_intro_dialog", "Y_skip_intro_dialog", "1191", "819", "StartQuit", "skip introduction dialog when accidentally restart on a new server")
;
# (21) setting_cogs
fstone_globcoord("setting_cogs", "X_setting_cogs", "Y_setting_cogs", "1284", "215", "StartQuit", "there are cases where settings hotkey is disabled - mouse only works")
;
# (22) close_window_cross
fstone_globcoord("close_window_cross", "X_close_window_cross", "Y_close_window_cross", "1360", "44", "StartQuit", "force close firefox window with cross in case a notification changes menu display")
;


### Tavern ###
# (1) tavern_main
fstone_globcoord("tavern_main", "X_tavern_main", "Y_tavern_main", "519", "810", "Tavern", "tavern building in town")
;
# (2) tavern_beer
fstone_globcoord("tavern_beer", "X_tavern_beer", "Y_tavern_beer", "543", "540", "Tavern", "tavern for beers")
;
# (3) tavern_scarab
fstone_globcoord("tavern_scarab", "X_tavern_scarab", "Y_tavern_scarab", "817", "539", "Tavern", "tavern for scarab")
;
# (4) beer_shop
fstone_globcoord("beer_shop", "X_beer_shop", "Y_beer_shop", "1260", "652", "Tavern", "shop for spending beers")
;
# (5) beer_to_token
fstone_globcoord("beer_to_token", "X_beer_to_token", "Y_beer_to_token", "383", "540", "Tavern", "converts 1500 beers into 5 tokens")
;
# (6) beer_tavern_toggl
fstone_globcoord("beer_tavern_toggl", "X_beer_tavern_toggl", "Y_beer_tavern_toggl", "1219", "803", "Tavern", "toggle for x1 x10 x50 pulls in beer tavern")
;
# (7) beer_tavern_play
fstone_globcoord("beer_tavern_play", "X_beer_tavern_play", "Y_beer_tavern_play", "689", "838", "Tavern", "play button in beer tavern")
;
# (8) beer_tavern_card
fstone_globcoord("beer_tavern_card", "X_beer_tavern_card", "Y_beer_tavern_card", "689", "672", "Tavern", "select a card to draw in beer tavern")
;
# (9) scarab_tavern_toggl
fstone_globcoord("scarab_tavern_toggl", "X_scarab_tavern_toggl", "Y_scarab_tavern_toggl", "1227", "793", "Tavern", "toggle for x1 x5 x10 x20 pulls in scarab tavern")
;
# (10) scarab_tavern_play
fstone_globcoord("scarab_tavern_play", "X_scarab_tavern_play", "Y_scarab_tavern_play", "696", "818", "Tavern", "play button in scarab tavern")
;
# (11) scarab_vault_tab
fstone_globcoord("scarab_vault_tab", "X_scarab_vault_tab", "Y_scarab_vault_tab", "1253", "318", "Tavern", "pharoh vault")
;
# (12) scarab_vault_toggl
fstone_globcoord("scarab_vault_toggl", "X_scarab_vault_toggl", "Y_scarab_vault_toggl", "1224", "850", "Tavern", "pharoh vault x1 x10 x50 toggle")
;
# (13) scarab_vault_open
fstone_globcoord("scarab_vault_open", "X_scarab_vault_open", "Y_scarab_vault_open", "801", "839", "Tavern", "pharoh vault opening")
;
# (14) release_beast
fstone_globcoord("release_beast", "X_release_beast", "Y_release_beast", "243", "589", "Tavern", "release the beast in main scarab screen; location is on the golden stone, in the circle above triangles")
;
# (15) craft_artifact
fstone_globcoord("craft_artifact", "X_craft_artifact", "Y_craft_artifact", "204", "856", "Tavern", "craft ancient artifact button location, on left side of chat icon in tavern, bottom the element wheel between earth and ether")
;


### WM ###
# (1) campaign_loot
fstone_globcoord("campaign_loot", "X_campaign_loot", "Y_campaign_loot", "150", "841", "WM", "claim campaign loot on wm map")
;
# (2) engi
fstone_globcoord("engi", "X_engi", "Y_engi", "906", "745", "WM", "engineer building in town")
;
# (3) engi_shop
fstone_globcoord("engi_shop", "X_engi_shop", "Y_engi_shop", "454", "561", "WM", "engineer workshop in building")
;
# (4) toolclaim
fstone_globcoord("toolclaim", "X_toolclaim", "Y_toolclaim", "1125", "656", "WM", "claim tools in engineer workshop")
;
# (5) camp_map
fstone_globcoord("camp_map", "X_camp_map", "Y_camp_map", "1271", "582", "WM", "wm campaign tab on map screen")
;
# (6) mission_button
fstone_globcoord("mission_button", "X_mission_button", "Y_mission_button", "1228", "857", "WM", "daily missions button on wm map")
;
# (7) liberations
fstone_globcoord("liberations", "X_liberations", "Y_liberations", "501", "724", "WM", "select liberation missions")
;
# (8) dungeons
fstone_globcoord("dungeons", "X_dungeons", "Y_dungeons", "874", "720", "WM", "select dungeon missions")
;
# (9) dungeon_1
fstone_globcoord("dungeon_1", "X_dungeon_1", "Y_dungeon_1", "544", "697", "WM", "dungeon mission 1 - left side")
;
# (10) dungeon_2
fstone_globcoord("dungeon_2", "X_dungeon_2", "Y_dungeon_2", "827", "699", "WM", "dungeon mission 2 - right side")
;
# (11) liberation_1
fstone_globcoord("liberation_1", "X_liberation_1", "Y_liberation_1", "234", "697", "WM", "liberation mission 1 - from left to right")
;
# (12) liberation_2
fstone_globcoord("liberation_2", "X_liberation_2", "Y_liberation_2", "516", "697", "WM", "liberation mission 2 - from left to right")
;
# (13) liberation_3
fstone_globcoord("liberation_3", "X_liberation_3", "Y_liberation_3", "794", "695", "WM", "liberation mission 3 - from left to right")
;
# (14) liberation_4
fstone_globcoord("liberation_4", "X_liberation_4", "Y_liberation_4", "1047", "695", "WM", "liberation mission 4 - from left to right")
;
# (15) liber_scroll_right
fstone_globcoord("liber_scroll_right", "X_liber_scroll_right", "SOLO_VAR", "1035", "0", "WM", "X coordinate of right mouse position for drag and drop - opening 5 and more liberation missions - scroll from right to left")
;
# (16) liber_scroll_left
fstone_globcoord("liber_scroll_left", "X_liber_scroll_left", "SOLO_VAR", "750", "0", "WM", "X coordinate of left mouse position for drag and drop - opening 5 and more liberation missions - scroll from right to left - the scroll step is 1 liberation mission card width")
;
# (17) liber_scroll
fstone_globcoord("liber_scroll", "Y_liber_scroll", "SOLO_VAR", "631", "0", "WM", "Y coordinate for liberation mission drag and drop - opening 5 and more liberations - the position is above start mission button")
;
# (18) north_island
fstone_globcoord("north_island", "X_north_island", "Y_north_island", "315", "811", "WM", "DEPRECATED")
;
# (19) battle_building
fstone_globcoord("battle_building", "X_battle_building", "Y_battle_building", "250", "296", "WM", "battle building in town for an access to campaign map without moving map bug")
;
# (20) campaign_access
fstone_globcoord("campaign_access", "X_campaign_access", "Y_campaign_access", "562", "529", "WM", "select campaign in battle building")
;
# (21) arena_fight_slot_3
fstone_globcoord("arena_fight_slot_3", "X_arena_fight_slot_3", "Y_arena_fight_slot_3", "870", "605", "WM", "third slot of arena fight (easiest)")
;
# (22) arena_fight_start
fstone_globcoord("arena_fight_start", "X_arena_fight_start", "Y_arena_fight_start", "677", "557", "WM", "start arena fight button")
;
]
